### PR TITLE
Add GitHub workflow

### PR DESCRIPTION
**Pull request by kdheepak**
Adding GitHub CI, since Travis CI doesn't seem to work anymore.

### CODE REVIEW

**Comment by kdheepak** [comment]
@matthiasbeyer let me know if you don't want github CI / if you prefer something else. I can make a new PR.

**Comment by kdheepak** [comment]
It looks like Travis-CI was running but just not showing the status on GitHub. But Travis-CI.org is going to be shut down shortly, and Travis-CI.com has limited free credits. If you are okay with it, we can remove `.travis.yml` file and disable Travis CI integration, and continue with just Github workflows. Thoughts?

**Comment by matthiasbeyer** [comment]
I'm okay with everything you're okay with!

:laughing: 

As long as it works and catches bugs, do what you think is best! Also, feel free to drop travis CI entirely!

**Comment by kdheepak** [comment]
Great! Thanks! :)

**Pull request merged**
