### PR TITLE
Support uda (2018 attempt)

### PR DESCRIPTION
**Pull request by maralorn**
So I tried to rebase the old PR on current master.
This made it necessary to update to thew newer serde version.

I also failed to stop my vim from rustfmt-ing the code …
If that is not fine with you I can try to cherrypick that out.

But udas are now supported and have working tests.
I would probably continue to creating PRs, with a bit refactoring and perhaps features, but first I'd like to now your opinion on this one.

### CODE REVIEW

**Comment by maralorn** [comment]
Hm, okay … Why didn't that fail locally? What do I have to do to run the extended tests locally? I just did "cargo check" …

**Comment by maralorn** [comment]
Okay, I understood the tests. Working on this.

**Comment by maralorn** [comment]
Okay, works for me. Waiting for review.

**Comment by matthiasbeyer** [comment]
Hey!

This looks awesome from what I see. I would be more comfortable, though, if you could split the style fixes out into a seperate PR. I am not against these changes, but review gets _much_ simpler with style changes split out!

Would you mind?

**Comment by maralorn** [comment]
There you go.
Not every commit is equally beautiful but the end result looks new reviewable to me.

**Pull request merged**
