### PR TITLE
Update version of task-hookrs

### PR DESCRIPTION
**Pull request by matthiasbeyer**
With the serde dependency updated, I guess we can release this as 0.2.3.

what do you think, @mario-kr ?

### CODE REVIEW

**Comment by mario-kr** [comment]
Considering [this](https://beyermatthias.de/blog/2016/10/25/breaking-the-code-without-touching/), I would go for version `0.3.0`.

**Comment by matthiasbeyer** [comment]
Hm. I'm, not sure we introduce breaking change here. All I did since 0.2.2 was updating the serde dependency, which is a non-breaking change...

**Comment by mario-kr** [comment]
the update from serde 0.7 -> 0.8 was also a non-breaking change

**Comment by matthiasbeyer** [comment]
But you're probably right.

Considering my work on the serde dependency to remove the boilerplate in this library, 0.4.0 might come up today as well... so what is your idea? Update task-hookrs to 0.3.0 _now_ and to 0.4.0 tomorrow, or waiting for the changes I'm working on (which clearly break the API) and release 0.3.0 then?

The point why I would like to have the other thing as seperate release is because I'm limiting the rust compiler version to 1.15 and newer with these changes then... which clearly means a new 0.x release instead of 0.x.y - IMHO.

**Comment by mario-kr** [comment]
Releasing two minor versions in a short amount of time is weird, but it's still `0.x.y`, so basically, you can do whatever you want.

**Comment by matthiasbeyer** [comment]
What would you do? You know I value your opinion on such things!

**Comment by matthiasbeyer** [comment]
Okay, I will wait until my big changeset lands and then release 0.3.0.

**Comment by mario-kr** [comment]
I probably would just push everything into one release due to laziness, so it's a bad idea to ask me how I'd do it.
I'm actually getting the feeling you're overthinking things here. Do what youre most comfortable with.

**Comment by mario-kr** [comment]
timing....

**Pull request closed without merging**
