### PR TITLE
[WIP] Add Taskwarrior Module

### PR DESCRIPTION
**Pull request by maralorn**
This PR will add the module tw with the functions `tw::query(query)` and `tw:save(tasks)`. They do pretty much, what you expect and are the basic ingredients for all interactions with taskwarrior. Most other interaction can probably be abstracted over this.

### CODE REVIEW

**Comment by maralorn** [comment]
I am open to suggestions in general. I know, that the tests are missing, but I wanted to know, if you agree with the direction where this is going.

Regarding your suggestions:
* I don't know, what you mean with query_with_command, what should be achieved by that?
* I don't feel comfortable with returning without catching errors from calling `save()`. That might even introduce race conditions. I am all for the futures solution, but that's not stable sadly. For now, I believe the user might want to spawn the function in a different thread maybe?
* I didn't go for the `foreign_links` option a) because I didn't succeed in commenting the error variant, which didn't work with the linter enforcement (which I think to be very awesome in general) b) I believe, what an io:Error means depends on the context, where we use it, so just Quickcasting to an TaskError::IO or something does not help the user very much. Instead I introduced two reasonable seeming ErrorKinds …

**Comment by maralorn** [comment]
I'd also appreciate tipps on how to implement the tests, when interfacing with taskwarrior.
I could just add some stuff to the travis config, but one cannot run that locally.

**Comment by matthiasbeyer** [comment]
> I don't know, what you mean with query_with_command, what should be achieved by that?

The `query_with_command` function would be the same as `query` only that the `Command` can be passed. That would give the user the power to do some modifications to it. In the documentation of the function there should be a warning that `stdout` is needed to be `piped` for this to work as expected, of course.

Other such functions could be thought of as well. In general, the `query()` function should be used, but others should at least be available with a big "Warning" section about how it works in detail and maybe even that their API should not be considered stable at any point.

> I am all for the futures solution, but that's not stable sadly. For now, I believe the user might want to spawn the function in a different thread maybe?

The idea with `futures` was for later, not now for the initial (re)design of the crate. Maybe that's even overkilll...

> [...] io:Error means depends on the context, where we use it, so just Quickcasting to an TaskError::IO or something does not help the user very much. Instead I introduced two reasonable seeming ErrorKinds …

:+1: 

> I'd also appreciate tipps on how to implement the tests, when interfacing with taskwarrior.

I guess best would be to have an `example/`-app which pushes some tasks into taskwarrior and a bash script that then asks taskwarrior whether these exist. I'm not sure whether this will be good enough.

> I could just add some stuff to the travis config, but one cannot run that locally.

Running them locally would pollute the users taskwarrior instance with testing tasks, so I would even say that's a benefit of putting the tests into the travis config. We could outsource them to a `./scripts/tests/` directory in bash scripts, though.

**Comment by maralorn** [comment]
I think I found a good solution for your concerns. What do you think?

**Comment by maralorn** [comment]
Do you think I can merge this without having tests?

**Comment by matthiasbeyer** [comment]
Hmh. I guess we should at least provide an example program that uses that interface directly, so we can show how it works and also test the functions by hand.

I'd be okay if these would be added by a separate PR though.
But I really think we should add such an example and I guess I won't do a release before we have one. :smile:

**Comment by maralorn** [comment]
Oh, sorry. I forgot to remove the [WIP] tag before the merge. I try to do better next time.^^

**Pull request merged**
