### PR TITLE
Update serde for Rust 1.15 (custom derive feature)

### PR DESCRIPTION
**Pull request by matthiasbeyer**
Update to use custom derive with rust 1.15.

This limits us to the latest stable compiler which was released today... and this will cause a minor version bumb from 0.2.2 to 0.3.0 (already filed in #45).

Does not work yet, though, as a test failes. I'm currently building rustc 1.15 on a VM at my university to check what's the problem.

### CODE REVIEW

**Comment by matthiasbeyer** [comment]
@mario-kr it works! ~500 lines removed and 23 added! That's the awesomeness of Rust 1.15! :tada:

**Comment by mario-kr** [comment]
you should make extra and doubly sure that optional keys are, well, optional in a given json input.

**Comment by matthiasbeyer** [comment]
What do you mean _exactly_? Taskwarrior -> Rust or Rust -> Taskwarrior?

**Comment by mario-kr** [comment]
both i guess?

**Comment by matthiasbeyer** [comment]
Hm. Not sure what you mean either direction. I didn't change functionality at all... just the interface (before, I parsed non-existing tags to an empty `Vec`, now I parse them to `None`, which is more correct IMO)

**Comment by mario-kr** [comment]
tw crashed because the json was not as it expected, remember? unfortunately, i cant remember what _exactly_ was wrong.

**Comment by matthiasbeyer** [comment]
Hm. True. Maybe we should have some tests for this... I mean with the actual taskwarrior binary...

**Comment by matthiasbeyer** [comment]
@mario-kr You were right... the last time we had the problem that `None` was serialized to `key => NULL` in the JSON output and `taskwarrior` couldn't handle that (it can now, as far as I know, but prior to 2.4 it couldn't).

We clearly should fix that.

**Comment by matthiasbeyer** [comment]
Awesome, serde has an option for this! :+1:

**Pull request merged**
