### PR TITLE
[after support-uda] Apply rustfmt

### PR DESCRIPTION
**Pull request by maralorn**
This change just applies rustfmt to all files.
This should create the same binary.

Should only be applied after #58.

### CODE REVIEW

**Comment by matthiasbeyer** [comment]
@maralorn I really welcome your changes! What would you say if I add you as contributor?

**Comment by matthiasbeyer** [comment]
WOW! This sounds really awesome! You definitively get contributor rights for task-hookrs!

I don't mind with the extra functionality in task-hookrs at all! The name is just a pun with the "hookrs" part :smile: ... so feel free to do this!

I also really welcome the part with libimagtodo you mentioned! Feel free to open an issue in the imag repository for further discussion (or, if you'd be more comfortable this way, via email)!

**Comment by matthiasbeyer** [comment]
@maralorn You just got contributor rights.

Make sure there are no `[TMP]`, `[WIP]` or `!fixup` commits in the branches you merge and always put changes in the changelog (we already forgot this for the UDA support...).

And never ever push to master, always work through PRs!

Happy hacking!

**Comment by matthiasbeyer** [comment]
Ah, and we do not do rebase merging. I just disabled this.

Now feel free to merge this PR as soon as CI succeeds!

**Comment by maralorn** [comment]
Oh, I think I missphrased that up there. The three bullets I made were alternative options. But if you are fine with it, which you seem to be, the first one would be my favorite.

**Comment by matthiasbeyer** [comment]
Yeah, I understood that and I'm fine with each of these options! :heart:

**Pull request merged**
