### PR TITLE
Update version of task-hookrs

### PR DESCRIPTION
**Pull request by matthiasbeyer**
Update version to 0.3.0

Superceeds #44

### CODE REVIEW

**Comment by matthiasbeyer** [comment]
Waiting for #46

**Comment by matthiasbeyer** [comment]
As the #47 and #45 are merged now... I guess we can release this, can't we, @mario-kr ?

**Comment by mario-kr** [comment]
yes

**Comment by matthiasbeyer** [comment]
I guess I cannot release, because my distro does not yet ship Rust 1.15 :cry:

**Pull request merged**
